# Generated by Django 5.2.5 on 2025-08-19 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplina', to='disciplina.disciplina')),
                ('matricula_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matricula', to='matricula.matricula')),
            ],
        ),
    ]
