# Generated by Django 5.2.5 on 2025-08-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='matricula',
            new_name='num_matricula',
        ),
    ]
