# Generated by Django 5.2.5 on 2025-08-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudante', '0002_rename_matricula_estudante_num_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='num_matricula',
            new_name='numero_matricula',
        ),
    ]
