# Generated by Django 5.2.5 on 2025-08-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('estudante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curso', to='curso.curso')),
                ('estudante_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudante', to='estudante.estudante')),
            ],
        ),
    ]
